apiVersion: v1
kind: Secret
metadata:
  name: hyperlofy-backend-secrets
  namespace: hyperlofy
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "hyperlofy_admin"
  SPRING_DATASOURCE_PASSWORD: "HyperlofySecurePass2026!"
  SPRING_DATA_REDIS_PASSWORD: "HyperlofyRedisPass2026!"
  JWT_SECRET: "hyperlofy_production_super_secret_jwt_signing_key_2026_min_256_bits_length!"
