package com.hyperlofy.backend.ai.learning;

public enum LearningType {
    CONVERSATION_COMPLETION,
    RECOMMENDATION_ACCEPTED,
    RECOMMENDATION_REJECTED,
    MERCHANT_SELECTED,
    MERCHANT_REJECTED,
    ORDER_PLACED,
    ORDER_CANCELLED,
    MEMORY_CREATED,
    MEMORY_UPDATED,
    VERIFICATION_PASSED,
    VERIFICATION_FAILED,
    PAYMENT_COMPLETED,
    CUSTOMER_CORRECTION,
    CUSTOMER_PREFERENCE_NEGATIVE
}
